version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: exchange  # Автоматически создаст базу данных exchange
      POSTGRES_USER: root
      POSTGRES_PASSWORD: testtest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/exchange
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: testtest
    depends_on:
      - postgres

volumes:
  pgdata: